name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: |
        cd Test-api
        ./mvnw clean install
        
    - name: Run tests
      run: |
        cd Test-api
        ./mvnw test
  
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd api-tester-ui
        npm ci
        
    - name: Build Angular app
      run: |
        cd api-tester-ui
        npm run build
        
    - name: Run tests
      run: |
        cd api-tester-ui
        npm test -- --watch=false --browsers=ChromeHeadless 